baseurl: ""
url: "/"
markdown: kramdown
source: "src"
destination: "public"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'

collections:
  works:
    output: true

exclude:
  - node_modules
